import os


class AzureConfig:
    AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
    AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY", "")
    AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4")
    AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-01")

    AZURE_BLOB_CONNECTION_STRING = os.getenv("AZURE_BLOB_CONNECTION_STRING", "")
    AZURE_BLOB_CONTAINER = os.getenv("AZURE_BLOB_CONTAINER", "bridal-images")

    AZURE_POSTGRESQL_HOST = os.getenv("AZURE_POSTGRESQL_HOST", "")
    AZURE_POSTGRESQL_PORT = os.getenv("AZURE_POSTGRESQL_PORT", "5432")
    AZURE_POSTGRESQL_DB = os.getenv("AZURE_POSTGRESQL_DB", "bridal_ai")
    AZURE_POSTGRESQL_USER = os.getenv("AZURE_POSTGRESQL_USER", "")
    AZURE_POSTGRESQL_PASSWORD = os.getenv("AZURE_POSTGRESQL_PASSWORD", "")


azure_config = AzureConfig()
